### ISSUE TITLE
configuració wifi RPI per connectar a MobilWifi Huawei

### ISSUE THREAD

**Issue by 4dan** [carduque/FeerBoxClient#7]
![connectar hua-hcb2 a 2018002](https://user-images.githubusercontent.com/32014087/35458407-85277696-02dc-11e8-8982-bf122661f7b2.png)
Després d'haver aconseguit configurar i canviar la contrasenya al HUA-HCB3 i connectar les dades del 2018003 via gsm. Ho intento igual amb  HUA-HCB2 a 2018002 i no deixa canviar contrasenya apareixent com open. Segons la nota "Note, WEP access points appear as 'Open'. RaspAP does not currently support connecting to WEP."   ##  Què podem fer?

**Comment by carduque** [comment]
Te la última versió de web admin? 2.0.1

El 26 ene. 2018 21:05, "4dan" <notifications@github.com> escribió:

[image: connectar hua-hcb2 a 2018002]
<https://user-images.githubusercontent.com/32014087/35458407-85277696-02dc-11e8-8982-bf122661f7b2.png>
Després d'haver aconseguit configurar i canviar la contrasenya al HUA-HCB3
i connectar les dades del 2018003 via gsm. Ho intento igual amb HUA-HCB2 a
2018002 i no deixa canviar contrasenya apareixent com open. Segons la nota
"Note, WEP access points appear as 'Open'. RaspAP does not currently
support connecting to WEP." ## Què podem fer?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/carduque/FeerBoxClient/issues/7>, or mute the thread

**Comment by 4dan** [comment]
Li he fet que s'actualitzi i ara te la 2.0.2.
Ho tornaré  a provar

2018-01-26 21:44 GMT+01:00 carduque <notifications@github.com>:

> Te la última versió de web admin? 2.0.1
>

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#12
